### ISSUE TITLE
Ace 12 image fails to build 

### ISSUE THREAD

**Issue by rranagit** [ot4i/ace-docker#164]
Hi, unable to build an image using the git repo and tar.gz file.

Command>> docker build -t ace-ibm-only --build-arg ACE_INSTALL=IBM_ACE_12.0.1.0_LNX_IBM_Z.tar.gz --file ubi/Dockerfile.aceonly .

IBM_ACE_12.0.1.0_LNX_IBM_Z.tar.gz is placed in deps folder.

=> CACHED [builder 14/21] RUN go test -v ./internal/...                                                                                                                  0.0s
 => CACHED [builder 15/21] RUN go test -v ./common/...                                                                                                                    0.0s
 => ERROR [builder 16/21] RUN go vet ./cmd/... ./internal/... ./common/...                                                                                               12.4s
 => CACHED [stage-1  2/19] COPY /licenses/ /licenses/                                                                                                                     0.0s
 => CACHED [stage-1  3/19] RUN microdnf update && microdnf install findutils util-linux unzip python3 tar procps openssl && microdnf clean all    && ln -s /usr/bin/pyth  0.0s
 => CACHED [stage-1  4/19] RUN microdnf reinstall tzdata -y                                                                                                               0.0s
 => CACHED [stage-1  5/19] COPY deps/OpenTracing/library/* ./opt/ACEOpenTracing/                                                                                          0.0s
 => CACHED [stage-1  6/19] COPY deps/OpenTracing/config/* ./etc/ACEOpenTracing/                                                                                           0.0s
 => CACHED [stage-1  7/19] WORKDIR /opt/ibm                                                                                                                               0.0s
------
 > [builder 16/21] RUN go vet ./cmd/... ./internal/... ./common/...:
#28 12.12 # github.com/ot4i/ace-docker/cmd/runaceserver
#28 12.12 cmd/runaceserver/signals.go:37:2: misuse of unbuffered os.Signal channel as argument to signal.Notify
#28 12.12 cmd/runaceserver/signals.go:59:6: misuse of unbuffered os.Signal channel as argument to signal.Notify
------
executor failed running [/bin/sh -c go vet ./cmd/... ./internal/... ./common/...]: exit code: 2

**Comment by mattbaileyuk** [comment]
This is a result of a change in Go1.17 which we're now picking up (https://golang.org/doc/go1.17 - 
New warning for calling signal.Notify on unbuffered channels); we'd encountered this elsewhere so going to port the change here which should resolve this.

**Comment by mattbaileyuk** [comment]
This should be resolved by the linked PR

**Comment by rranagit** [comment]
PR fixed the error but now giving  error 


 => [stage-1 16/19] COPY ubi/generic_invalid/application.descriptor /home/aceuser/temp                                                                                                                                                                                   0.0s
 => ERROR [stage-1 17/19] RUN /opt/ibm/ace-12/ace make registry global accept license silently   && useradd -u 1000 -d /home/aceuser -G mqbrkrs,wheel aceuser   && mkdir -p /var/mqsi   && mkdir -p /home/aceuser/initial-config   && su - -c '. /opt/ibm/ace-12/server  0.3s
------
 > [stage-1 17/19] RUN /opt/ibm/ace-12/ace make registry global accept license silently   && useradd -u 1000 -d /home/aceuser -G mqbrkrs,wheel aceuser   && mkdir -p /var/mqsi   && mkdir -p /home/aceuser/initial-config   && su - -c '. /opt/ibm/ace-12/server/bin/mqsiprofile && mqsicreateworkdir /home/aceuser/ace-server'   && chmod -R 777 /home/aceuser   && chmod -R 777 /var/mqsi   && su - -c '. /opt/ibm/ace-12/server/bin/mqsiprofile && echo $MQSI_JREPATH && chmod g+w $MQSI_JREPATH/lib/security/cacerts'   && chmod -R 777 /home/aceuser/temp   && chmod 777 /opt/ibm/ace-12/server/ODBC/dsdriver/odbc_cli/clidriver/license:
#43 0.307 /lib/ld64.so.1: No such file or directory
#43 0.310 /lib/ld64.so.1: No such file or directory
------
executor failed running [/bin/sh -c /opt/ibm/ace-12/ace make registry global accept license silently   && useradd -u 1000 -d /home/aceuser -G mqbrkrs,wheel aceuser   && mkdir -p /var/mqsi   && mkdir -p /home/aceuser/initial-config   && su - -c '. /opt/ibm/ace-12/server/bin/mqsiprofile && mqsicreateworkdir /home/aceuser/ace-server'   && chmod -R 777 /home/aceuser   && chmod -R 777 /var/mqsi   && su - -c '. /opt/ibm/ace-12/server/bin/mqsiprofile && echo $MQSI_JREPATH && chmod g+w $MQSI_JREPATH/lib/security/cacerts'   && chmod -R 777 /home/aceuser/temp   && chmod 777 /opt/ibm/ace-12/server/ODBC/dsdriver/odbc_cli/clidriver/license]: exit code: 1

**Comment by rranagit** [comment]
@mattbaileyuk @andyedwardsibm - Am i missing something here? Still cant build ace12 image.

**Comment by andyedwardsibm** [comment]
I've just run through the build of the `Dockerfile.aceonly` docker file and it completed successfully.  For me though, the call to `RUN /opt/ibm/ace-12/ace make registry global accept license silently ...` is step 42 of 50.  Are you building the vanilla `Dockerfile.aceonly` file or a modified version of it?

If I exec into the final image and poke around, there is no `/lib/ld64.so.1` file either (and there isn't in `registry.access.redhat.com/ubi8/ubi-minimal` either) so the error is accurate, but I'm not sure what is trying to use that file in the compound `RUN` statement.  It _might_ be the `useradd` call as that does try to use _a_ `/lib/ld-...` library but in a different place

```
ldd /usr/sbin/useradd 
	linux-vdso.so.1 (0x00007ffe82798000)
	libaudit.so.1 => /lib64/libaudit.so.1 (0x00007fce65902000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fce656d8000)
	libsemanage.so.1 => /lib64/libsemanage.so.1 (0x00007fce65497000)
	libacl.so.1 => /lib64/libacl.so.1 (0x00007fce6528e000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007fce65088000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fce64cc3000)
	libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007fce64abd000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fce6489d000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fce64619000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fce64415000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fce65d57000)
	libsepol.so.1 => /lib64/libsepol.so.1 (0x00007fce64163000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fce63f52000)
```

It's almost like the `ubi8/ubi-minimal` you're building from is somehow corrupted (or something other than `ubi8/ubi-minimal`).

Things you can try:
- try building on a different machine to see if it's a corrupt image/layer in your docker cache
- modify the Dockerfile so that each `RUN` command is run separately to narrow down which one is triggering the error.  Or you could only build up to the line before this failing `RUN`, then exec in and run each command separately - that might be better for poking around to see what's wrong
